FROM apache/spark:4.1.2

USER root

# Install Python packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install \
        kafka-python \
        psycopg2-binary

# Create a real home directory for the spark user
RUN mkdir -p /home/spark && \
    chown -R spark:spark /home/spark && \
    usermod -d /home/spark spark

ENV HOME=/home/spark
ENV PYTHONPATH=/opt/logiroute

WORKDIR /opt/logiroute

USER spark